### ISSUE TITLE
Unable to bypass virus detection

### ISSUE THREAD

**Issue by eyoung417** [emiyl/nxDumpMerger#3]
With the latest releases that are not done in 7-zip it appears that the .zip and exe are both flagging when downloading. This happens in any browser i have tried. The built in virus detection is flagging. However the 7-zip file does not flag as a virus.

**Comment by emiyl** [comment]
Weird, try downloading the python script itself?

**Comment by eyoung417** [comment]
python script by itself downloads but the .exe and .zip do not. 7-zip still allowed download. Maybe something in 7z that masks the zipped file?

**Comment by Cuteseal** [comment]
you can disable realtime protection in windows defender's settings, then download the file in internet explorer, since internet explorer is rather primitive, it uses windows built in anti-virus, rather than just using a built in one, but if the file still won't download, you can download the python script, basically download python if you haven't already, then open a cmd terminal in the script's directory, then type the exact name (including the extension ".py") into the terminal, then it starts up, and if that's a little too much for you I wrote a batch script, you place the thing into the same directory as the py script and double click it, and away you go. (the reason it's a zip is because github doesn't allow batch files)
[run the script.zip](https://github.com/emiyl/nxDumpMerger/files/5963028/run.the.script.zip)

**Comment by Jwboucher94** [comment]
another option is you can add an exclusion for a specific folder. Label it so you know which one it is and so you don't use it for anything else, but that will allow you to get past the virus detection as windows will not scan that folder. But definitely remain cautious of this as if you download something else there with an actual virus you could compromise your system.

**Comment by lepinwalrus16** [comment]
Windows is flagging this as a trojan virus.

**Comment by NortPort** [comment]
Why is it that when I download the zip file, Windows Defender detects a Skeeyah Trojan?

**Comment by emiyl** [comment]
It's a false positive caused by the program I use to convert python scripts to .exe files. If you don't trust the .exe file, download the [python script](https://github.com/emiyl/nxDumpMerger/raw/master/nxDumpMerger.py) itself and run that.
